### ISSUE TITLE
connect to docker-gitlab

### ISSUE THREAD

**Issue by veggiemonk** [lazyfrosch/docker-mattermost#2]
Hi,

I saw your answer on sameersbn/docker-gitlab#426. Thank you for making a nice image. 
Can you explain a little how to integrate mattermost to gitlab? 
I mean SSO and more precisely, how to use the DB of gitlab (postgresql) instead of a new MariaDB ? 
This is to limit the number of db running. 

Thank you so much, any advice would be highly appreciated.

Cheers

**Comment by lazyfrosch** [comment]
I guess it all depends on linking to the shared postgresql container.

Everything else is in config.json.

I'm currently not sure if I want to maintain a image for mattermost, but take my code and use it :)
